#!/bin/bash

read -p "🗑️ Masukkan username yang ingin dihapus: " user

if [[ -f /etc/xray/user/$user.json ]]; then
  rm -f /etc/xray/user/$user.json
  sed -i "/^### $user /d" /etc/xray/vless.json
  sed -i "/^### $user /d" /etc/xray/vmess.json
  echo "✅ User $user berhasil dihapus."
  systemctl restart xray
else
  echo "❌ User $user tidak ditemukan."
fi
