#!/bin/bash

read -p "🔒 Masukkan username: " user
read -p "🔢 Batas login maksimum (misal: 1): " maxlogin

echo "$maxlogin" > /etc/xray/user/${user}.limit
echo "✅ Batas login $user diset ke $maxlogin"
